const test = require('tape')
const normalize = require('.')

test('normalize', (t) => {
  t.equal(normalize('./foo///b/../b/c.js'), 'foo/b/b/c.js')
  t.equal(normalize('/foo/../../../bar'), '/foo/bar')
  t.equal(normalize('a//b//../b'), 'a/b/b')
  t.equal(normalize('a//b//./c'), 'a/b/c')
  t.equal(normalize('a//b//.'), 'a/b')
  t.equal(normalize('/a/b/c/../../../x/y/z'), '/a/b/c/x/y/z')
  t.equal(normalize('///..//./foo/.//bar'), '/foo/bar')
  t.equal(normalize('bar/foo../../'), 'bar/foo../')
  t.equal(normalize('bar/foo../..'), 'bar/foo..')
  t.equal(normalize('bar/foo../../baz'), 'bar/foo../baz')
  t.equal(normalize('bar/foo../'), 'bar/foo../')
  t.equal(normalize('bar/foo..'), 'bar/foo..')
  t.equal(normalize('../foo../../../bar'), 'foo../bar')
  t.equal(normalize('../.../.././.../../../bar'), 'bar')
  t.equal(normalize('../../../foo/../../../bar'), 'foo/bar')
  t.equal(normalize('../../../foo/../../../bar/../../'), 'foo/bar/')
  t.equal(normalize('../foobar/barfoo/foo/../../../bar/../../'), 'foobar/barfoo/foo/bar/')
  t.equal(normalize('../.../../foobar/../../../bar/../../baz'), 'foobar/bar/baz')
  t.equal(normalize('%%'), '%%')
  t.equal(normalize(''), '/')
  t.throws(() => normalize(1), /Expected a string, got a number/)
  t.end()
})
